/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpelareRouteImport } from './routes/spelare'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexIndexRouteImport } from './routes/index.index'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedAdminLogosRouteImport } from './routes/_authenticated/admin.logos'
import { Route as ApiPublicHooksPregameEmailsRouteImport } from './routes/api/public/hooks/pregame-emails'
import { Route as ApiPublicHooksPostgameEmailsRouteImport } from './routes/api/public/hooks/postgame-emails'

const SpelareRoute = SpelareRouteImport.update({
  id: '/spelare',
  path: '/spelare',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexIndexRoute = IndexIndexRouteImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLogosRoute = AuthenticatedAdminLogosRouteImport.update({
  id: '/admin/logos',
  path: '/admin/logos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksPregameEmailsRoute =
  ApiPublicHooksPregameEmailsRouteImport.update({
    id: '/api/public/hooks/pregame-emails',
    path: '/api/public/hooks/pregame-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPostgameEmailsRoute =
  ApiPublicHooksPostgameEmailsRouteImport.update({
    id: '/api/public/hooks/postgame-emails',
    path: '/api/public/hooks/postgame-emails',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schema': typeof SchemaRoute
  '/spelare': typeof SpelareRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/index/': typeof IndexIndexRoute
  '/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/api/public/hooks/postgame-emails': typeof ApiPublicHooksPostgameEmailsRoute
  '/api/public/hooks/pregame-emails': typeof ApiPublicHooksPregameEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schema': typeof SchemaRoute
  '/spelare': typeof SpelareRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/index': typeof IndexIndexRoute
  '/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/api/public/hooks/postgame-emails': typeof ApiPublicHooksPostgameEmailsRoute
  '/api/public/hooks/pregame-emails': typeof ApiPublicHooksPregameEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schema': typeof SchemaRoute
  '/spelare': typeof SpelareRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/index/': typeof IndexIndexRoute
  '/_authenticated/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/api/public/hooks/postgame-emails': typeof ApiPublicHooksPostgameEmailsRoute
  '/api/public/hooks/pregame-emails': typeof ApiPublicHooksPregameEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/reset-password'
    | '/schema'
    | '/spelare'
    | '/notifications'
    | '/index/'
    | '/admin/logos'
    | '/api/public/hooks/postgame-emails'
    | '/api/public/hooks/pregame-emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/reset-password'
    | '/schema'
    | '/spelare'
    | '/notifications'
    | '/index'
    | '/admin/logos'
    | '/api/public/hooks/postgame-emails'
    | '/api/public/hooks/pregame-emails'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compare'
    | '/reset-password'
    | '/schema'
    | '/spelare'
    | '/_authenticated/notifications'
    | '/index/'
    | '/_authenticated/admin/logos'
    | '/api/public/hooks/postgame-emails'
    | '/api/public/hooks/pregame-emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchemaRoute: typeof SchemaRoute
  SpelareRoute: typeof SpelareRoute
  IndexIndexRoute: typeof IndexIndexRoute
  ApiPublicHooksPostgameEmailsRoute: typeof ApiPublicHooksPostgameEmailsRoute
  ApiPublicHooksPregameEmailsRoute: typeof ApiPublicHooksPregameEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spelare': {
      id: '/spelare'
      path: '/spelare'
      fullPath: '/spelare'
      preLoaderRoute: typeof SpelareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/': {
      id: '/index/'
      path: '/index'
      fullPath: '/index/'
      preLoaderRoute: typeof IndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logos': {
      id: '/_authenticated/admin/logos'
      path: '/admin/logos'
      fullPath: '/admin/logos'
      preLoaderRoute: typeof AuthenticatedAdminLogosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/pregame-emails': {
      id: '/api/public/hooks/pregame-emails'
      path: '/api/public/hooks/pregame-emails'
      fullPath: '/api/public/hooks/pregame-emails'
      preLoaderRoute: typeof ApiPublicHooksPregameEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/postgame-emails': {
      id: '/api/public/hooks/postgame-emails'
      path: '/api/public/hooks/postgame-emails'
      fullPath: '/api/public/hooks/postgame-emails'
      preLoaderRoute: typeof ApiPublicHooksPostgameEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedAdminLogosRoute: typeof AuthenticatedAdminLogosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedAdminLogosRoute: AuthenticatedAdminLogosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchemaRoute: SchemaRoute,
  SpelareRoute: SpelareRoute,
  IndexIndexRoute: IndexIndexRoute,
  ApiPublicHooksPostgameEmailsRoute: ApiPublicHooksPostgameEmailsRoute,
  ApiPublicHooksPregameEmailsRoute: ApiPublicHooksPregameEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
